### ISSUE TITLE
PMLR page count slightly off when last pages contains only figures

### ISSUE THREAD

**Issue by HKervadec** [MIDL-Conference/MIDLLatexTemplate#10]
Before I forget, for the fifth time,  to post that one

We noticed that the page number (at the top of the first page of each article) was sometimes off by 1-2 pages. A quick investigation seems to show that pages containing only floats (figures, tables) aren't counted. 

(http://proceedings.mlr.press/v121/kervadec20a/kervadec20a.pdf for instance, but there are others). The numbering shows `Proceedings of Machine Learning Research 121:365–380`, but the pages go up to 381. 

I've just checked quickly with volume 102, couldn't find one with only figures at the end -- don't know if this is an old problem or a subtle regression introduced by the PMLR template or us.

Def a painful bug to track down.

**Comment by tvercaut** [comment]
This definitely revives some painful memories....
https://github.com/MIDL-Conference/MIDL2019_FullPapers_Proceedings/blob/f3a213a143e933e1cfdd4a5fff7100be6d77e957/Volume102/bass19/bass19.tex#L419

**Comment by tvercaut** [comment]
I have filed a bug report [here](https://www.dickimaw-books.com/bugtracker.php?action=view&key=168) with the following MWE (and workaround):
```latex
\documentclass[pmlr]{jmlr} % Include author names

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{mwe}

\title[Short Title]{Full Title of Article}

\author{
	\Name{Author A \nametag{$^{1}$}} \Email{authora@test.com}\\
	\addr $^{1}$ Address, City, Countryy \AND
	\Name{Author B \nametag{$^{2}$}} \Email{authorb@test.com} \\
	\addr $^{2}$ Address, City, Country
      }


\begin{document}

\maketitle

\begin{abstract}
\blindtext
\end{abstract}

\begin{keywords}
List of keywords, comma separated.
\end{keywords}

\section{Introduction}

\Blindtext[5][2]

\acks{\blindtext}

\appendix
\section{Appendix}

% Uncomment the next line for a work around to get page numbers right when last page is a float
%\clearpage

\begin{figure}[htbp]
 % Caption and label go in the first argument and the figure contents
 % go in the second argument
\floatconts
  {fig:example}
  {\caption{Example Image}}
  {\includegraphics[width=0.5\linewidth]{example-image}}
\end{figure}

\end{document}
```

**Comment by HKervadec** [comment]
I just experimented on the 2020 proceedings, it seems that adding the following at the end of `midl.cls` did the trick:
```latex
\RequirePackage{lastpage}
\renewcommand*{\@jmlrpages}{\pageref{jmlrstart}--\pageref{LastPage}}
```

With the original command being 
```latex
\providecommand*\@jmlrpages{\pageref{jmlrstart}--\pageref{jmlrend}}
```

It does not seem that `\pageref{jmlrend}` is used somewhere, so I do not think it will cause any other ill side-effect.
