### ISSUE TITLE
`\midlotherjointauthor` not showing the footnote mark

### ISSUE THREAD

**Issue by mlaves** [MIDL-Conference/MIDLLatexTemplate#13]
When using `\midlotherjointauthor` on the second author to show equal contribution, the footnote mark is not showing properly. Moving `\addtocounter{footnote}{-1}` after `\footnotemark` in the definition of `\midlotherjointauthor` fixed the issue. I will create a pull request.

**Comment by HKervadec** [comment]
Ok yeah, I reproduced the issue on my paper, and tested your fix. Looks good, thanks a lot for the fix.
