### ISSUE TITLE
Migrate tests from travis to github actions

### ISSUE THREAD

**Issue by nlessmann** [MIDL-Conference/MIDLLatexTemplate#15]
Looks like the tests are not run anymore.

**Comment by tvercaut** [comment]
Not sure why this is the case... There is an authorisation issue showing up on travis but I don't know how to solve it.
> Could not authorize build request for MIDL-Conference/MIDLLatexTemplate.

That said, switching to github actions makes sense

**Comment by nlessmann** [comment]
Maybe you need to select the "Free" plan? That's suggested as a solution for this problem here: https://stackoverflow.com/questions/41034694/travis-could-not-authorize-build-request/41078031

**Comment by tvercaut** [comment]
Thanks. I had seen this, tried it and it didn't help. I now realise I had done it for my own travis plan rather than the one from teh MIDL organisation. The build is running now.

**Comment by tvercaut** [comment]
The mac OS CI is broken but there doesn't seen to be a fix at the moment:
https://github.com/travis-ci/travis-ci/issues/8922#issuecomment-896057522

We should probably disable it or move to another CI infrastructure that supports more recent mac versions.

**Comment by tvercaut** [comment]
Thanks to @fepegar, we now have an example of GHA for latex that works across linux+tex live, mac + mactex and windows+miktex:
https://github.com/cai4cai/XCLThesisTemplate/blob/master/.github/workflows/build.yml

@nlessmann: Can you look into porting this here?

**Comment by nlessmann** [comment]
Awesome, works great, see https://github.com/MIDL-Conference/MIDLLatexTemplate/actions/runs/1453826727
