### ISSUE TITLE
referencing to arxiv papers

### ISSUE THREAD

**Issue by aliechoes** [MIDL-Conference/MIDLLatexTemplate#16]
Hi. Thanks for providing the template.

I have a question about referencing to arxiv papers. After adding the arxiv paper in the bibliography, I only see that the name of the paper and authors are printed in the references. However I would like to add eprint and other information there. Would you please help me with that? I'd appreciate it

Cheers

**Comment by nlessmann** [comment]
Could you post the bibtex string that you are using for the arxiv paper? That would make it easier to debug.

**Comment by tvercaut** [comment]
I added an example of good practice here:
https://github.com/MIDL-Conference/MIDLLatexTemplate/blob/a3d25298a4abf0d66679e1157bb9b9e63210c301/midl-samplebibliography.bib#L10-L18

**Comment by aliechoes** [comment]
Hi Thanks for the reply. This is the bibtex string

```
@ARTICLE{Azizi2021-td,
  title         = "Big {Self-Supervised} Models Advance Medical Image
                   Classification",
  author        = "Azizi, Shekoofeh and Mustafa, Basil and Ryan, Fiona and
                   Beaver, Zachary and Freyberg, Jan and Deaton, Jonathan and
                   Loh, Aaron and Karthikesalingam, Alan and Kornblith, Simon
                   and Chen, Ting and Natarajan, Vivek and Norouzi, Mohammad",
  month         =  jan,
  year          =  2021,
  archivePrefix = "arXiv",
  primaryClass  = "eess.IV",
  eprint        = "2101.05224"
}
```
Would it be possible to get the `eprint` for example in there refereces?

**Comment by tvercaut** [comment]
The bibliography style used by PMLR doesn't support `eprint` directly and that's not something we can change on our side.

To provide a reference to arXiv, you can either use the `howpublished` field with a `@misc` entry or if you want to stick to a `@article` entry type, you can make use of the `note` field.

**Comment by aliechoes** [comment]
thanks for the answer! `note` did the job :) 

Cheers
