### ISSUE TITLE
Intended behaviour of JMLR fields

### ISSUE THREAD

**Issue by Timsey** [MIDL-Conference/MIDLLatexTemplate#18]
The `midl-fullpaper.tex` header contains the following block:

> \jmlrvolume{-- Under Review}
\jmlryear{2022}
\jmlrworkshop{Full Paper -- MIDL 2022 submission}
\editors{Under Review for MIDL 2022}

It is unclear to me whether these values should be changed to for accepted papers (and if so, to what). Looking at papers from previous years suggests something like the following, which requires knowledge of the exact proceedings volume + syntax for that.

> \jmlrvolume{PROCEEDINGS VOLUME}
\jmlryear{2022}
\jmlrworkshop{Full Paper -- MIDL 2022}
[remove editors line]

I was wondering if this is the desired behaviour, and what (if anything) should be done with these lines for camera-ready submissions?

**Comment by HKervadec** [comment]
>>     \jmlrvolume{PROCEEDINGS VOLUME}
>>     \jmlryear{2022}
>>     \jmlrworkshop{Full Paper -- MIDL 2022}
>>     [remove editors line]
>
>I was wondering if this is the desired behaviour, and what (if anything) should be done with these lines for camera-ready submissions?

(Disclaimer, I am not involved in the organization this year, so you'll have to wait for the official instructions. But this can give you a head-up.)

The process (at least for the last three years) was for the authors to send the `.tex` sources files to the program chairs, whom would do the final compilation.
This is required to handle the page numbers properly (as you can see here: http://proceedings.mlr.press/v102/ ), set the PMLR volume number, and ensure that every paper actually used the same template.

The compilation process would first strip the jmlr definitions with `sed`, and then inject the final one with a fancy pdflatex command:
```bash
pdflatex -interaction=nonstopmode %O '\expandafter\def\csname @jmlryear\endcsname{2020}\expandafter\def\csname @jmlrvolume\endcsname{121}\expandafter\def\csname @jmlrworkshop\endcsname{MIDL 2020 -- Full paper track}\def\startpage{NNN}\input{%S}'
``` 

So in the end, you probably won't need to focus too much on that. For Openreview and arxiv, feel free to put anything, as they are pre-print. 

Hope that helps, 

Hoel

**Comment by Timsey** [comment]
Thanks, that answers my concerns!
