### ISSUE TITLE
First page break in anonymous mode

### ISSUE THREAD

**Issue by HaleAkrami** [MIDL-Conference/MIDLLatexTemplate#21]
When I add my text and change the document to anonymous, the first page break doesn't work and Latex gives error that there is no \begin{document}. Can you please check it?

**Comment by nlessmann** [comment]
We can add a test for this - but please remember that submissions should not be anonymous this year (MIDL 2022).

**Comment by nlessmann** [comment]
Thanks for reporting this issue, it has now been fixed!
