### ISSUE TITLE
latex error: file mwe.sty not found

### ISSUE THREAD

**Issue by JunMa11** [MIDL-Conference/MIDLLatexTemplate#6]
https://github.com/MIDL-Conference/MIDLLatexTemplate/blob/cb9cb6975e947ff3389295cb35d63e80c1b772e2/midl-fullpaper.tex#L9

![捕获](https://user-images.githubusercontent.com/19947331/71319546-ba94b600-24da-11ea-8e78-c0a272e7bc61.PNG)

**Comment by HKervadec** [comment]
The package `mwe` is missing in your LaTeX install. You should add it. https://www.ctan.org/pkg/mwe

However, since this package is used to produce dummy images, it is only useful for the sample example ; you can drop it altogether and put your actual images in your document.

**Comment by JunMa11** [comment]
thank for your help very much.
