### ISSUE TITLE
Issue with subcaptions

### ISSUE THREAD

**Issue by ieee8023** [MIDL-Conference/MIDLLatexTemplate#7]
Can you add an example of subcaptions working to the example paper? I cannot get it working. 

For this code:
```
\begin{figure}
     \centering
     \begin{subfigure}[b]{0.25\textwidth}
         \centering
         \includegraphics[width=0.2\textwidth]{example-image-a}
         \caption{$y=x$}
         \label{fig:y equals x}
     \end{subfigure}%
     \begin{subfigure}[b]{0.25\textwidth}
         \centering
         \includegraphics[width=0.2\textwidth]{example-image-b}
         \caption{$y=3sinx$}
         \label{fig:three sin x}
     \end{subfigure}%
     \begin{subfigure}[b]{0.25\textwidth}
         \centering
         \includegraphics[width=0.2\textwidth]{example-image-c}
         \caption{$y=5/x$}
         \label{fig:five over x}
     \end{subfigure}
        \caption{Three simple graphs}
        \label{fig:three graphs}
\end{figure}
```
I get this. The figures captions do not work as they do with other styles. If I change them to subcaption then then work but this little (a) will exist on top of the figure.

<img width="585" alt="Screen Shot 2020-01-06 at 1 01 13 PM" src="https://user-images.githubusercontent.com/446367/71837530-a4632a00-3084-11ea-96f4-8bd8e1174424.png">

This code should work as I took it from here: https://www.overleaf.com/learn/latex/How_to_Write_a_Thesis_in_LaTeX_(Part_3):_Figures,_Subfigures_and_Tables

**Comment by tvercaut** [comment]
To avoid duplicating information, our [README](https://github.com/MIDL-Conference/MIDLLatexTemplate/blob/master/README.md) points to the JMLR template documentation: http://mirrors.ctan.org/macros/latex/contrib/jmlr/jmlr.pdf

Did you try the recommended subfigure code from there?
```latex
\begin{figure}[htbp]
\floatconts
  {fig:example2}% label for whole figure
  {\caption{An Example Figure with Subfigures.}}% caption for whole figure
  {%
    \subfigure[An example subcaption]{%
      \label{fig:pic1}% label for this sub-figure
      \includegraphics[width=0.4\linewidth]{example-image}
    }\qquad % space out the images a bit
    \subfigure[Another example subcaption]{%
      \label{fig:pic2}% label for this sub-figure
      \includegraphics[width=0.4\linewidth]{example-image}
    }
  }
\end{figure}
```

**Comment by ieee8023** [comment]
Ok that works! floatconts seems like a super ugly command though. 

Maybe can you have a error thrown when someone tries to import subcaption? It gives warning when you try to import subfig already.

**Comment by tvercaut** [comment]
Not sure how to add the warning. Feel free to open a PR for it or refer that suggestion to the main JMLR template maintainers. I'll close this issue for now.

If you strongly feel that the example with subfigures should be embeded in our sample file, feel free to reopen this.

**Comment by tvercaut** [comment]
I found out how to prevent the inclusion of problematic packages and added subcaption to the list.
